### ISSUE TITLE
Help on implementation and setup...

### ISSUE THREAD

**Issue by ctschach** [gsicilia82/Espresense_iobroker#1]
I just came across this page and it's great that someone if already working on implementing this for iobroker.

I try taking your script, create a new javascript in iobrokers script engine and paste your code. It complains that it could not finde mathjs:

`javascript.0 (25643) script.js.0_-_Utilities.ESPresence: Error: Cannot find module 'mathjs'
`

Even though I use javascript for web programming, I never used it in iobroker. I still stick with blockly for my tasks.

**Comment by gsicilia82** [comment]
Hi, you need to put mathjs in Javascript instance configuration as additional module.
I would prefer to avoid library dependency, but in this case it is used for matrix multiplications (in trilateration function).

I have not included any readme, because for now, it was tested only from me and another user.

You can find additional information in this thread:

https://forum.iobroker.net/topic/19928/mqtt-bluetooth-ble-anwesenheitserkennung-mit-esp32/105
